import React, { useState } from 'react';
import { useTheme } from '../contexts/ThemeContext';
import useCircuitStore from '../../store/useCircuitStore';

const AdvancedExportFormats = () => {
  const { currentTheme } = useTheme;
  const { nodes, edges } = useCircuitStore();
  
  const [exportFormat, setExportFormat] = useState('json');
  const [exportSettings, setExportSettings] = useState({
    includeMetadata: true,
    includeAnnotations: false,
    includeTimestamp: true,
    includeVersion: true,
    compression: false,
    format: 'pretty'
  });

  // Export format definitions
  const exportFormats = [
    {
      id: 'json',
      name: 'JSON Netlist',
      description: 'Structured JSON representation of circuit',
      extension: 'json',
      mimeType: 'application/json',
      icon: 'JSON'
    },
    {
      id: 'spice',
      name: 'SPICE Netlist',
      description: 'SPICE circuit simulation format',
      extension: 'cir',
      mimeType: 'text/plain',
      icon: 'SPICE'
    },
    {
      id: 'edif',
      name: 'EDIF',
      description: 'Electronic Design Interchange Format',
      extension: 'edif',
      mimeType: 'text/plain',
      icon: 'EDIF'
    },
    {
      id: 'cdl',
      name: 'CDL Netlist',
      description: 'Cadence Design Language format',
      extension: 'cdl',
      mimeType: 'text/plain',
      icon: 'CDL'
    },
    {
      id: 'hdl',
      name: 'Verilog HDL',
      description: 'Hardware Description Language',
      extension: 'v',
      mimeType: 'text/plain',
      icon: 'HDL'
    },
    {
      id: 'vhdl',
      name: 'VHDL',
      description: 'VHSIC Hardware Description Language',
      extension: 'vhd',
      mimeType: 'text/plain',
      icon: 'VHDL'
    }
  ];

  // Generate JSON netlist
  const generateJSONNetlist = () => {
    const netlist = {
      metadata: {
        format: 'JSON Netlist',
        version: '1.0',
        created: new Date().toISOString(),
        tool: 'Chip Designer',
        nodes: nodes.length,
        edges: edges.length
      },
      circuit: {
        name: 'circuit_design',
        description: 'Generated circuit design',
        nodes: nodes.map(node => ({
          id: node.id,
          type: node.data.label,
          position: node.position,
          data: {
            label: node.data.label,
            value: node.data.value,
            // Additional node properties
            parameters: getNodeParameters(node)
          }
        })),
        edges: edges.map(edge => ({
          id: edge.id,
          source: edge.source,
          target: edge.target,
          sourceHandle: edge.sourceHandle,
          targetHandle: edge.targetHandle,
          data: edge.data || {}
        }))
      },
      analysis: {
        nodeTypes: getNodeTypes(),
        connectivity: analyzeConnectivity(),
        complexity: calculateComplexity()
      }
    };

    // Add optional metadata
    if (exportSettings.includeMetadata) {
      netlist.metadata.annotations = {
        timestamp: exportSettings.includeTimestamp ? new Date().toISOString() : undefined,
        version: exportSettings.includeVersion ? '1.0.0' : undefined
      };
    }

    return JSON.stringify(netlist, null, exportSettings.format === 'pretty' ? 2 : 0);
  };

  // Generate SPICE netlist
  const generateSPICENetlist = () => {
    let spice = '';
    
    // Header
    spice += '* SPICE Netlist Generated by Chip Designer\n';
    spice += `* Created: ${new Date().toISOString()}\n`;
    spice += `* Nodes: ${nodes.length}, Edges: ${edges.length}\n\n`;
    
    // Circuit name
    spice += 'CIRCUIT_DESIGN\n';
    
    // Generate node mappings
    const nodeMap = {};
    let nodeCounter = 1;
    
    nodes.forEach(node => {
      if (node.data.label === 'INPUT' || node.data.label === 'OUTPUT') {
        nodeMap[node.id] = node.data.name || node.id;
      } else {
        nodeMap[node.id] = `N${nodeCounter++}`;
      }
    });
    
    // Add components
    nodes.forEach(node => {
      const spiceComponent = generateSPICEComponent(node, nodeMap);
      if (spiceComponent) {
        spice += `${spiceComponent}\n`;
      }
    });
    
    // Add voltage sources for inputs
    nodes.filter(n => n.data.label === 'INPUT').forEach(node => {
      const nodeName = nodeMap[node.id];
      spice += `V${nodeName} ${nodeName} 0 PULSE(0 5 0 1n 1n 10n 20n)\n`;
    });
    
    // Add analysis commands
    spice += '\n* Analysis\n';
    spice += '.TRAN 1n 100n\n';
    spice += '.OP\n';
    spice += '.AC DEC 10 1 1G\n';
    
    // Add output commands
    spice += '\n* Output\n';
    nodes.filter(n => n.data.label === 'OUTPUT').forEach(node => {
      const nodeName = nodeMap[node.id];
      spice += `.PRINT TRAN V(${nodeName})\n`;
      spice += `.PLOT TRAN V(${nodeName})\n`;
    });
    
    spice += '\n.END';
    
    return spice;
  };

  // Generate SPICE component
  const generateSPICEComponent = (node, nodeMap) => {
    const nodeName = nodeMap[node.id];
    
    switch (node.data.label) {
      case 'AND':
        return generateSPICEGate(node, nodeMap, 'AND');
      case 'OR':
        return generateSPICEGate(node, nodeMap, 'OR');
      case 'NOT':
        return generateSPICEGate(node, nodeMap, 'NOT');
      case 'XOR':
        return generateSPICEGate(node, nodeMap, 'XOR');
      case 'NAND':
        return generateSPICEGate(node, nodeMap, 'NAND');
      case 'NOR':
        return generateSPICEGate(node, nodeMap, 'NOR');
      case 'XNOR':
        return generateSPICEGate(node, nodeMap, 'XNOR');
      default:
        return null;
    }
  };

  // Generate SPICE gate
  const generateSPICEGate = (node, nodeMap, gateType) => {
    const inputEdges = edges.filter(e => e.target === node.id);
    const outputEdges = edges.filter(e => e.source === node.id);
    
    if (inputEdges.length === 0 || outputEdges.length === 0) return null;
    
    const inputs = inputEdges.map(edge => nodeMap[edge.source]);
    const output = nodeMap[outputEdges[0].target];
    
    const subcircuits = {
      'AND': 'AND2',
      'OR': 'OR2',
      'NOT': 'INV',
      'XOR': 'XOR2',
      'NAND': 'NAND2',
      'NOR': 'NOR2',
      'XNOR': 'XNOR2'
    };
    
    const subcircuit = subcircuits[gateType];
    if (!subcircuit) return null;
    
    return `X${node.id} ${inputs.join(' ')} ${output} ${subcircuit}`;
  };

  // Generate EDIF format
  const generateEDIF = () => {
    let edif = '';
    
    // Header
    edif += '(edif circuit_design\n';
    edif += '  (edifVersion 2 0 0)\n';
    edif += `  (edifLevel 0)\n`;
    edif += `  (keywordMap (keywordLevel 0))\n`;
    edif += `  (status (written (timeStamp ${new Date().toISOString()}))\n`;
    edif += `    (program "Chip Designer" (version "1.0.0")))\n`;
    edif += `  (library design_lib\n`;
    edif += `    (edifLevel 0)\n`;
    edif += `    (technology (numberDefinition (scale 1 (unit e))\n`;
    edif += `      (gridMap (gridSpacing 1.0 1.0))))\n`;
    
    // Add cells
    const cellTypes = getNodeTypes();
    cellTypes.forEach(cellType => {
      edif += `    (cell ${cellType}\n`;
      edif += `      (cellType GENERIC)\n`;
      edif += `      (view netlist\n`;
      edif += `        (viewType NETLIST)\n`;
      edif += `        (interface\n`;
      
      // Add ports
      const cellNodes = nodes.filter(n => n.data.label === cellType);
      if (cellNodes.length > 0) {
        const node = cellNodes[0];
        const inputEdges = edges.filter(e => e.target === node.id);
        const outputEdges = edges.filter(e => e.source === node.id);
        
        inputEdges.forEach((edge, index) => {
          edif += `          (port IN${index + 1} (direction INPUT))\n`;
        });
        
        outputEdges.forEach((edge, index) => {
          edif += `          (port OUT${index + 1} (direction OUTPUT))\n`;
        });
      }
      
      edif += `        )\n`;
      edif += `      )\n`;
      edif += `    )\n`;
    });
    
    // Add instances
    edif += `    (cell circuit\n`;
    edif += `      (cellType GENERIC)\n`;
    edif += `      (view netlist\n`;
    edif += `        (viewType NETLIST)\n`;
    edif += `        (interface\n`;
    
    // Add external ports
    nodes.filter(n => n.data.label === 'INPUT' || n.data.label === 'OUTPUT').forEach(node => {
      const direction = node.data.label === 'INPUT' ? 'INPUT' : 'OUTPUT';
      edif += `          (port ${node.id} (direction ${direction}))\n`;
    });
    
    edif += `        )\n`;
    edif += `        (contents\n`;
    
    // Add instances
    nodes.filter(n => n.data.label !== 'INPUT' && n.data.label !== 'OUTPUT').forEach(node => {
      edif += `          (instance ${node.id} (viewRef netlist (cellRef ${node.data.label}\n`;
      edif += `            (libraryRef design_lib)))\n`;
      edif += `            (property TRANSFORM (string "1 0 0")))\n`;
    });
    
    // Add nets
    const netCounter = { current: 1 };
    edges.forEach(edge => {
      const netName = `NET${netCounter.current++}`;
      edif += `          (net ${netName}\n`;
      edif += `            (joined\n`;
      edif += `              (portRef ${edge.source} (instanceRef ${edge.source}))\n`;
      edif += `              (portRef ${edge.target} (instanceRef ${edge.target}))\n`;
      edif += `            ))\n`;
    });
    
    edif += `        )\n`;
    edif += `      )\n`;
    edif += `    )\n`;
    edif += `  )\n`;
    edif += ')';
    
    return edif;
  };

  // Generate CDL netlist
  const generateCDL = () => {
    let cdl = '';
    
    // Header
    cdl += '* CDL Netlist Generated by Chip Designer\n';
    cdl += `* Created: ${new Date().toISOString()}\n\n`;
    
    // Add subcircuits
    const subcircuits = generateCDLSubcircuits();
    cdl += subcircuits;
    
    // Add main circuit
    cdl += '\n* Main Circuit\n';
    cdl += '.SUBCKT MAIN_CIRCUIT ';
    
    // Add I/O ports
    const inputNodes = nodes.filter(n => n.data.label === 'INPUT');
    const outputNodes = nodes.filter(n => n.data.label === 'OUTPUT');
    
    const ports = [...inputNodes.map(n => n.id), ...outputNodes.map(n => n.id)];
    cdl += ports.join(' ');
    cdl += '\n';
    
    // Add instances
    nodes.filter(n => n.data.label !== 'INPUT' && n.data.label !== 'OUTPUT').forEach(node => {
      const instance = generateCDLInstance(node);
      if (instance) {
        cdl += `${instance}\n`;
      }
    });
    
    cdl += '.ENDS MAIN_CIRCUIT\n';
    
    return cdl;
  };

  // Generate CDL subcircuits
  const generateCDLSubcircuits = () => {
    let subcircuits = '';
    
    const gateSubcircuits = {
      'AND': {
        inputs: 2,
        definition: '.SUBCKT AND2 A B Y\n* AND gate implementation\nR1 A 1 1K\nR2 B 2 1KX1 1 2 3 0 VCC\nQ1 3 0 0 QNPN\nR3 3 Y 1K\n.ENDS AND2'
      },
      'OR': {
        inputs: 2,
        definition: '.SUBCKT OR2 A B Y\n* OR gate implementation\nR1 A 1 1K\nR2 B 2 1K\nQ1 1 0 0 QNPN\nQ2 2 0 0 QNPN\nR3 1 3 1K\nR4 2 3 1K\nQ3 3 0 0 QNPN\nR5 3 Y 1K\n.ENDS OR2'
      },
      'NOT': {
        inputs: 1,
        definition: '.SUBCKT INV A Y\n* Inverter implementation\nR1 A 1 1K\nQ1 1 0 0 QNPN\nR2 1 Y 1K\n.ENDS INV'
      }
    };
    
    Object.entries(gateSubcircuits).forEach(([gateType, subcircuit]) => {
      subcircuits += `\n* ${gateType} Subcircuit\n`;
      subcircuits += `${subcircuit.definition}\n`;
    });
    
    return subcircuits;
  };

  // Generate CDL instance
  const generateCDLInstance = (node) => {
    const inputEdges = edges.filter(e => e.target === node.id);
    const outputEdges = edges.filter(e => e.source === node.id);
    
    if (inputEdges.length === 0 || outputEdges.length === 0) return null;
    
    const inputs = inputEdges.map(edge => edge.source);
    const output = outputEdges[0].target;
    
    const instanceNames = {
      'AND': 'AND2',
      'OR': 'OR2',
      'NOT': 'INV',
      'XOR': 'XOR2',
      'NAND': 'NAND2',
      'NOR': 'NOR2',
      'XNOR': 'XNOR2'
    };
    
    const instanceName = instanceNames[node.data.label];
    if (!instanceName) return null;
    
    return `X${node.id} ${inputs.join(' ')} ${output} ${instanceName}`;
  };

  // Generate Verilog HDL
  const generateVerilogHDL = () => {
    let verilog = '';
    
    // Header
    verilog += '// Verilog HDL Generated by Chip Designer\n';
    verilog += `// Created: ${new Date().toISOString()}\n\n`;
    
    // Module definition
    verilog += 'module circuit_design(\n';
    
    // Add ports
    const inputNodes = nodes.filter(n => n.data.label === 'INPUT');
    const outputNodes = nodes.filter(n => n.data.label === 'OUTPUT');
    
    const ports = [];
    inputNodes.forEach(node => {
      ports.push(`    input ${node.id}`);
    });
    outputNodes.forEach(node => {
      ports.push(`    output ${node.id}`);
    });
    
    verilog += ports.join(',\n');
    verilog += '\n);\n\n';
    
    // Add internal wires
    const internalNodes = nodes.filter(n => 
      n.data.label !== 'INPUT' && n.data.label !== 'OUTPUT'
    );
    
    if (internalNodes.length > 0) {
      verilog += '// Internal signals\n';
      internalNodes.forEach(node => {
        verilog += `wire ${node.id};\n`;
      });
      verilog += '\n';
    }
    
    // Add gate instances
    verilog += '// Gate instances\n';
    internalNodes.forEach(node => {
      const instance = generateVerilogInstance(node);
      if (instance) {
        verilog += `${instance}\n`;
      }
    });
    
    verilog += '\nendmodule\n';
    
    return verilog;
  };

  // Generate Verilog instance
  const generateVerilogInstance = (node) => {
    const inputEdges = edges.filter(e => e.target === node.id);
    const outputEdges = edges.filter(e => e.source === node.id);
    
    if (inputEdges.length === 0 || outputEdges.length === 0) return null;
    
    const inputs = inputEdges.map(edge => edge.source);
    const output = outputEdges[0].target;
    
    const gateModules = {
      'AND': 'and_gate',
      'OR': 'or_gate',
      'NOT': 'not_gate',
      'XOR': 'xor_gate',
      'NAND': 'nand_gate',
      'NOR': 'nor_gate',
      'XNOR': 'xnor_gate'
    };
    
    const moduleName = gateModules[node.data.label];
    if (!moduleName) return null;
    
    return `${moduleName} ${node.id} (${output}, ${inputs.join(', ')});`;
  };

  // Generate VHDL
  const generateVHDL = () => {
    let vhdl = '';
    
    // Header
    vhdl += '-- VHDL Generated by Chip Designer\n';
    vhdl += `-- Created: ${new Date().toISOString()}\n\n`;
    
    // Library declarations
    vhdl += 'library IEEE;\n';
    vhdl += 'use IEEE.STD_LOGIC_1164.ALL;\n';
    vhdl += 'use IEEE.NUMERIC_STD.ALL;\n\n';
    
    // Entity declaration
    vhdl += 'entity circuit_design is\n';
    vhdl += '    Port (\n';
    
    // Add ports
    const inputNodes = nodes.filter(n => n.data.label === 'INPUT');
    const outputNodes = nodes.filter(n => n.data.label === 'OUTPUT');
    
    const ports = [];
    inputNodes.forEach(node => {
      ports.push(`        ${node.id} : in  STD_LOGIC`);
    });
    outputNodes.forEach(node => {
      ports.push(`        ${node.id} : out  STD_LOGIC`);
    });
    
    vhdl += ports.join(';\n');
    vhdl += '\n    );\n';
    vhdl += 'end circuit_design;\n\n';
    
    // Architecture
    vhdl += 'architecture Behavioral of circuit_design is\n\n';
    
    // Add signals
    const internalNodes = nodes.filter(n => 
      n.data.label !== 'INPUT' && n.data.label !== 'OUTPUT'
    );
    
    if (internalNodes.length > 0) {
      vhdl += '-- Internal signals\n';
      internalNodes.forEach(node => {
        vhdl += `signal ${node.id} : STD_LOGIC;\n`;
      });
      vhdl += '\n';
    }
    
    // Component declarations
    vhdl += '-- Component declarations\n';
    const components = getVHDLComponents();
    vhdl += components;
    vhdl += '\n';
    
    // Component instances
    vhdl += '-- Component instances\n';
    vhdl += 'begin\n\n';
    
    internalNodes.forEach(node => {
      const instance = generateVHDLInstance(node);
      if (instance) {
        vhdl += `${instance}\n\n`;
      }
    });
    
    vhdl += 'end Behavioral;\n';
    
    return vhdl;
  };

  // Get VHDL components
  const getVHDLComponents = () => {
    let components = '';
    
    const componentTemplates = {
      'AND': `component and_gate
    Port ( A : in  STD_LOGIC;
           B : in  STD_LOGIC;
           Y : out STD_LOGIC);
    end component;`,
      'OR': `component or_gate
    Port ( A : in  STD_LOGIC;
           B : in  STD_LOGIC;
           Y : out STD_LOGIC);
    end component;`,
      'NOT': `component not_gate
    Port ( A : in  STD_LOGIC;
           Y : out STD_LOGIC);
    end component;`,
      'XOR': `component xor_gate
    Port ( A : in  STD_LOGIC;
           B : in  STD_LOGIC;
           Y : out STD_LOGIC);
    end component;`
    };
    
    Object.values(componentTemplates).forEach(template => {
      components += `${template}\n\n`;
    });
    
    return components;
  };

  // Generate VHDL instance
  const generateVHDLInstance = (node) => {
    const inputEdges = edges.filter(e => e.target === node.id);
    const outputEdges = edges.filter(e => e.source === node.id);
    
    if (inputEdges.length === 0 || outputEdges.length === 0) return null;
    
    const inputs = inputEdges.map(edge => edge.source);
    const output = outputEdges[0].target;
    
    const componentNames = {
      'AND': 'and_gate',
      'OR': 'or_gate',
      'NOT': 'not_gate',
      'XOR': 'xor_gate',
      'NAND': 'nand_gate',
      'NOR': 'nor_gate',
      'XNOR': 'xnor_gate'
    };
    
    const componentName = componentNames[node.data.label];
    if (!componentName) return null;
    
    let instance = `${componentName}_inst : ${componentName}\n`;
    instance += `    port map (\n`;
    
    const portMap = inputs.map(input => `        ${input} => ${input}`);
    portMap.push(`        Y => ${output}`);
    
    instance += portMap.join(',\n');
    instance += '\n    );';
    
    return instance;
  };

  // Helper functions
  const getNodeParameters = (node) => {
    const params = {};
    
    // Add common parameters
    if (node.data.value !== undefined) {
      params.value = node.data.value;
    }
    
    // Add type-specific parameters
    switch (node.data.label) {
      case 'D_FLIP_FLOP':
        params.setupTime = 0.05;
        params.holdTime = 0.02;
        params.propagationDelay = 0.15;
        break;
      case 'JK_FLIP_FLOP':
        params.setupTime = 0.06;
        params.holdTime = 0.03;
        params.propagationDelay = 0.18;
        break;
    }
    
    return params;
  };

  const getNodeTypes = () => {
    const types = new Set();
    nodes.forEach(node => {
      if (node.data.label !== 'INPUT' && node.data.label !== 'OUTPUT') {
        types.add(node.data.label);
      }
    });
    return Array.from(types);
  };

  const analyzeConnectivity = () => {
    const connectivity = {
      inputs: nodes.filter(n => n.data.label === 'INPUT').length,
      outputs: nodes.filter(n => n.data.label === 'OUTPUT').length,
      connections: edges.length,
      isolated: 0
    };
    
    // Find isolated nodes
    const connectedNodes = new Set();
    edges.forEach(edge => {
      connectedNodes.add(edge.source);
      connectedNodes.add(edge.target);
    });
    
    connectivity.isolated = nodes.filter(n => !connectedNodes.has(n.id)).length;
    
    return connectivity;
  };

  const calculateComplexity = () => {
    let complexity = 0;
    
    // Base complexity from node count
    complexity += nodes.length * 1;
    
    // Add complexity for edges
    complexity += edges.length * 0.5;
    
    // Add complexity for sequential elements
    const sequentialNodes = nodes.filter(n => 
      n.data.label.includes('FLIP_FLOP') || n.data.label.includes('FF')
    );
    complexity += sequentialNodes.length * 2;
    
    return Math.round(complexity);
  };

  // Generate export content
  const generateExportContent = () => {
    switch (exportFormat) {
      case 'json':
        return generateJSONNetlist();
      case 'spice':
        return generateSPICENetlist();
      case 'edif':
        return generateEDIF();
      case 'cdl':
        return generateCDL();
      case 'hdl':
        return generateVerilogHDL();
      case 'vhdl':
        return generateVHDL();
      default:
        return '';
    }
  };

  // Download export
  const downloadExport = () => {
    const format = exportFormats.find(f => f.id === exportFormat);
    if (!format) return;
    
    const content = generateExportContent();
    const blob = new Blob([content], { type: format.mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `circuit.${format.extension}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Preview export
  const previewExport = () => {
    const content = generateExportContent();
    console.log('Export preview:', content);
  };

  return (
    <div
      style={{
        height: '100%',
        backgroundColor: currentTheme.background,
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Header */}
      <div
        style={{
          padding: '16px',
          borderBottom: `1px solid ${currentTheme.border}`,
        }}
      >
        <div
          style={{
            fontSize: '16px',
            fontWeight: '600',
            color: currentTheme.text.primary,
            marginBottom: '12px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
          }}
        >
          <span style={{ fontSize: '20px' }}>Export</span>
          Advanced Export Formats
        </div>

        <div
          style={{
            display: 'flex',
            gap: '8px',
            flexWrap: 'wrap',
          }}
        >
          <button
            onClick={downloadExport}
            style={{
              padding: '6px 12px',
              backgroundColor: currentTheme.primary,
              color: 'white',
              border: 'none',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '11px',
              fontWeight: '500',
              transition: 'all 0.2s ease',
            }}
          >
            Download
          </button>

          <button
            onClick={previewExport}
            style={{
              padding: '6px 12px',
              backgroundColor: currentTheme.secondary,
              color: 'white',
              border: 'none',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '11px',
              fontWeight: '500',
              transition: 'all 0.2s ease',
            }}
          >
            Preview
          </button>
        </div>
      </div>

      {/* Export Content */}
      <div
        style={{
          flex: 1,
          overflow: 'hidden',
          padding: '16px',
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
        }}
      >
        {/* Format Selection */}
        <div>
          <div
            style={{
              fontSize: '14px',
              fontWeight: '600',
              color: currentTheme.text.primary,
              marginBottom: '12px',
            }}
          >
            Export Format
          </div>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: '8px',
            }}
          >
            {exportFormats.map(format => (
              <div
                key={format.id}
                style={{
                  backgroundColor: exportFormat === format.id ? `${currentTheme.primary}15` : currentTheme.surface,
                  border: exportFormat === format.id ? `2px solid ${currentTheme.primary}` : `1px solid ${currentTheme.border}`,
                  borderRadius: '6px',
                  padding: '8px',
                  cursor: 'pointer',
                  transition: 'all 0.2s ease',
                }}
                onClick={() => setExportFormat(format.id)}
              >
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    marginBottom: '4px',
                  }}
                >
                  <div
                    style={{
                      width: '24px',
                      height: '24px',
                      backgroundColor: currentTheme.primary,
                      borderRadius: '6px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: '10px',
                      fontWeight: '600',
                      color: 'white',
                    }}
                  >
                    {format.icon}
                  </div>
                  <div
                    style={{
                      fontSize: '12px',
                      fontWeight: '600',
                      color: currentTheme.text.primary,
                    }}
                  >
                    {format.name}
                  </div>
                </div>
                <div
                  style={{
                    fontSize: '10px',
                    color: currentTheme.text.secondary,
                  }}
                >
                  {format.description}
                </div>
                <div
                  style={{
                    fontSize: '9px',
                    color: currentTheme.text.secondary,
                    marginTop: '4px',
                  }}
                >
                  .{format.extension}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Export Settings */}
        <div>
          <div
            style={{
              fontSize: '14px',
              fontWeight: '600',
              color: currentTheme.text.primary,
              marginBottom: '8px',
            }}
          >
            Export Settings
          </div>

          <div
            style={{
              backgroundColor: currentTheme.surface,
              border: `1px solid ${currentTheme.border}`,
              borderRadius: '6px',
              padding: '12px',
            }}
          >
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: '1fr 1fr',
                gap: '12px',
              }}
            >
              <div>
                <label
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    fontSize: '11px',
                    color: currentTheme.text.secondary,
                    cursor: 'pointer',
                    marginBottom: '4px',
                  }}
                >
                  <input
                    type="checkbox"
                    checked={exportSettings.includeMetadata}
                    onChange={(e) => setExportSettings(prev => ({ ...prev, includeMetadata: e.target.checked }))}
                  />
                  Include metadata
                </label>

                <label
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    fontSize: '11px',
                    color: currentTheme.text.secondary,
                    cursor: 'pointer',
                    marginBottom: '4px',
                  }}
                >
                  <input
                    type="checkbox"
                    checked={exportSettings.includeAnnotations}
                    onChange={(e) => setExportSettings(prev => ({ ...prev, includeAnnotations: e.target.checked }))}
                  />
                  Include annotations
                </label>

                <label
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    fontSize: '11px',
                    color: currentTheme.text.secondary,
                    cursor: 'pointer',
                    marginBottom: '4px',
                  }}
                >
                  <input
                    type="checkbox"
                    checked={exportSettings.includeTimestamp}
                    onChange={(e) => setExportSettings(prev => ({ ...prev, includeTimestamp: e.target.checked }))}
                  />
                  Include timestamp
                </label>

                <label
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    fontSize: '11px',
                    color: currentTheme.text.secondary,
                    cursor: 'pointer',
                    marginBottom: '4px',
                  }}
                >
                  <input
                    type="checkbox"
                    checked={exportSettings.includeVersion}
                    onChange={(e) => setExportSettings(prev => ({ ...prev, includeVersion: e.target.checked }))}
                  />
                  Include version
                </label>
              </div>

              <div>
                <label
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    fontSize: '11px',
                    color: currentTheme.text.secondary,
                    cursor: 'pointer',
                    marginBottom: '4px',
                  }}
                >
                  <input
                    type="checkbox"
                    checked={exportSettings.compression}
                    onChange={(e) => setExportSettings(prev => ({ ...prev, compression: e.target.checked }))}
                  />
                  Compression
                </label>

                <div
                  style={{
                    marginBottom: '4px',
                  }}
                >
                  <label
                    style={{
                      display: 'block',
                      fontSize: '11px',
                      color: currentTheme.text.secondary,
                      marginBottom: '4px',
                    }}
                  >
                    Format
                  </label>
                  <select
                    value={exportSettings.format}
                    onChange={(e) => setExportSettings(prev => ({ ...prev, format: e.target.value }))}
                    style={{
                      width: '100%',
                      padding: '4px',
                      backgroundColor: currentTheme.background,
                      border: `1px solid ${currentTheme.border}`,
                      borderRadius: '4px',
                      fontSize: '10px',
                      color: currentTheme.text.primary,
                    }}
                  >
                    <option value="pretty">Pretty</option>
                    <option value="compact">Compact</option>
                    <option value="minified">Minified</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Circuit Statistics */}
        <div>
          <div
            style={{
              fontSize: '14px',
              fontWeight: '600',
              color: currentTheme.text.primary,
              marginBottom: '8px',
            }}
          >
            Circuit Statistics
          </div>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
              gap: '12px',
            }}
          >
            <div
              style={{
                backgroundColor: currentTheme.surface,
                border: `1px solid ${currentTheme.border}`,
                borderRadius: '8px',
                padding: '12px',
              }}
            >
              <div
                style={{
                  fontSize: '12px',
                  fontWeight: '600',
                  color: currentTheme.text.primary,
                  marginBottom: '4px',
                }}
              >
                Nodes
              </div>
              <div
                style={{
                  fontSize: '20px',
                  fontWeight: '600',
                  color: currentTheme.primary,
                }}
              >
                {nodes.length}
              </div>
            </div>

            <div
              style={{
                backgroundColor: currentTheme.surface,
                border: `1px solid ${currentTheme.border}`,
                borderRadius: '8px',
                padding: '12px',
              }}
            >
              <div
                style={{
                  fontSize: '12px',
                  fontWeight: '600',
                  color: currentTheme.text.primary,
                  marginBottom: '4px',
                }}
              >
                Edges
              </div>
              <div
                style={{
                  fontSize: '20px',
                  fontWeight: '600',
                  color: currentTheme.primary,
                }}
              >
                {edges.length}
              </div>
            </div>

            <div
              style={{
                backgroundColor: currentTheme.surface,
                border: `1px solid ${currentTheme.border}`,
                borderRadius: '8px',
                padding: '12px',
              }}
            >
              <div
                style={{
                  fontSize: '12px',
                  fontWeight: '600',
                  color: currentTheme.text.primary,
                  marginBottom: '4px',
                }}
              >
                Inputs
              </div>
              <div
                style={{
                  fontSize: '20px',
                  fontWeight: '600',
                  color: currentTheme.primary,
                }}
              >
                {nodes.filter(n => n.data.label === 'INPUT').length}
              </div>
            </div>

            <div
              style={{
                backgroundColor: currentTheme.surface,
                border: `1px solid ${currentTheme.border}`,
                borderRadius: '8px',
                padding: '12px',
              }}
            >
              <div
                style={{
                  fontSize: '12px',
                  fontWeight: '600',
                  color: currentTheme.text.primary,
                  marginBottom: '4px',
                }}
              >
                Outputs
              </div>
              <div
                style={{
                  fontSize: '20px',
                  fontWeight: '600',
                  color: currentTheme.primary,
                }}
              >
                {nodes.filter(n => n.data.label === 'OUTPUT').length}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdvancedExportFormats;
